# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
     - "*"

pr:
  branches:
    include:
      - develop
      - release
      - main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: GetResourceGroupName
    pool:
      vmImage: ubuntu-latest
    steps:
    # Gets resource group name for AKS cluster to use for Ingress Controller and Service
    # Please define pipeline the variables:
    # - RESOURCE_GROUP_NAME
    # - KUBERNETES_CLUSTER_NAME
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'VH-Norsk Gjenvinning-DING(5)(41d3ebaf-2ed7-487b-8ffb-f9ccfade8414)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: '##vso[task.setvariable variable=ResourceGroupName;isoutput=true]az aks show --resource-group $1 --name $2 --query nodeResourceGroup -o tsv'
        arguments: '$(RESOURCE_GROUP_NAME) $(KUBERNETES_CLUSTER_NAME)'
    - bash: |
        echo $(ResourceGroupName)

  - job: RunMaven
    dependsOn: ReadResourceGroupName
    steps:
    - task: Maven@3
      inputs:
        mavenPomFile: 'pom.xml'
        mavenOptions: '-Xmx3072m'
        javaHomeOption: 'JDKVersion'
        jdkVersionOption: '1.11'
        jdkArchitectureOption: 'x64'
        publishJUnitResults: true
        testResultsFiles: '**/surefire-reports/TEST-*.xml'
        goals: 'package'
