INSERT INTO sales_roles (default_power_of_attorney_fa, default_power_of_attorney_oa, description, role_name) VALUES (1, 1, 'Kundeveileder - frontlinr', 'KV');
INSERT INTO sales_roles (default_power_of_attorney_fa, default_power_of_attorney_oa, description, role_name) VALUES (1, 1, 'Priskoordinator', 'PK');
INSERT INTO sales_roles (default_power_of_attorney_fa, default_power_of_attorney_oa, description, role_name) VALUES (6, 6, 'Regionsjef', 'RS');
INSERT INTO sales_roles (default_power_of_attorney_fa, default_power_of_attorney_oa, description, role_name) VALUES (6, 6, 'Salgsleder/salgssjef lokalt', 'SL');
INSERT INTO sales_roles (default_power_of_attorney_fa, default_power_of_attorney_oa, description, role_name) VALUES (2, 2, 'Salgskonsulent', 'SK');
INSERT INTO sales_roles (default_power_of_attorney_fa, default_power_of_attorney_oa, description, role_name) VALUES (6, 6, 'Chancellor', 'Admin');
INSERT INTO sales_roles (default_power_of_attorney_fa, default_power_of_attorney_oa, description, role_name) VALUES (5, 5, 'KAM nasjonalt', 'KN');
INSERT INTO sales_roles (default_power_of_attorney_fa, default_power_of_attorney_oa, description, role_name) VALUES (3, 3, 'Fagkonsulent FA', 'FA');
INSERT INTO sales_roles (default_power_of_attorney_fa, default_power_of_attorney_oa, description, role_name) VALUES (6, 6, 'Distriktssjef', 'DR');
INSERT INTO sales_roles (default_power_of_attorney_fa, default_power_of_attorney_oa, description, role_name) VALUES (6, 6, 'Backoffice', 'BO');

INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (100,'StorOslo','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (101,'Asker/Bærum','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (102,'Romerike','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (103,'Vestby/Moss','Østfold');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (104,'Skien','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (105,'Larvik','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (106,'Tønsberg','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (107,'Drammen','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (108,'Kongsberg','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (109,'Hønefoss','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (110,'Molde','Midt-Nord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (112,'Ålesund','Nord-Vest');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (113,'Kristiansund','Midt-Nord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (114,'Namsos','Midt-Nord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (115,'Trondheim','Midt-Nord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (117,'Verdal','Midt-Nord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (118,'NordNorge','Midt-Nord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (119,'Holmestrand','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (120,'Hamarregionen','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (121,'Østerdalen','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (122,'GLTregionen','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (123,'HRAregionen','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (124,'Lillehammerregionen','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (125,'Gudbrandsdalen','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (126,'Valdres','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (127,'Sarpsborg/Fredriksta','Østfold');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (128,'IndreØstfold/Halden','Østfold');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (129,'Romerike','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (130,'Arendal','Agder');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (131,'Kristiansand','Agder');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (132,'Stavanger','Rogaland');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (133,'Haugesund','Rogaland');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (134,'Bergen','Hordaland');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (135,'Førde','Nord-Vest');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (136,'Florø','Nord-Vest');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (138,'Kragerø','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (139,'Ørsta','Nord-Vest');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (141,'Oslo(GMP)','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (142,'Follo','Oslofjord');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (144,'Ryfylke','Rogaland');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (146,'Mandal','Agder');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (147,'Lyngdal','Agder');
INSERT INTO sale_office_power_of_attorney_matrix(sales_office, sales_office_name, region) VALUES (149,'Setesdalen','Agder');
