import no.ding.pk.domain.bo.BoReportCondition;
import no.ding.pk.domain.bo.SuggestedConditionCodeKeyCombination;

global no.ding.pk.domain.bo.SuggestedConditionCodeKeyCombination suggestion;
dialect "mvel"

rule "Salgskontor per material per sone"
    when
        BoReportCondition(hasSalesOrg == true)
    then
        System.out.println("First rule hit");
        suggestion.setConditionCode("ZPTR");
        suggestion.setKeyCombination("Salgskontor per material per sone");
        suggestion.setKeyCombinationTableName("A615");
end
rule "Salgskontor per material per avfall per sone"
    when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == true)
        BoReportCondition(isWaste == true)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZPTR");
        suggestion.setKeyCombination("Salgskontor per material per avfall per sone");
        suggestion.setKeyCombinationTableName("A783");
end

rule "Salgskontor per material per avfall per sone Per AP"
    when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == true)
        BoReportCondition(isWaste == true)
        BoReportCondition(hasDevicePlacement == true)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZPTR");
        suggestion.setKeyCombination("Salgskontor per material per avfall per sone Per AP");
        suggestion.setKeyCombinationTableName("A791");
end

rule "Salgskontor per material per sone per AP"
when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == true)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == true)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZPTR");
        suggestion.setKeyCombination("Salgskontor per material per sone per AP");
        suggestion.setKeyCombinationTableName("A790");
end

rule "Rabatt per kunde/material"
when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZR05");
        suggestion.setKeyCombination("Rabatt per kunde/material");
        suggestion.setKeyCombinationTableName("A704");
end

rule "Rabatt salgskontor per kunde per material per avfall 01"
when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == true)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZR05");
        suggestion.setKeyCombination("Rabatt salgskontor per kunde per material per avfall");
        suggestion.setKeyCombinationTableName("?");
end

rule "Rabatt salgskontor per kunde per material per apparattype 01"
when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == true)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZR05");
        suggestion.setKeyCombination("Rabatt salgskontor per kunde per material per apparattype");
        suggestion.setKeyCombinationTableName("A766");
end

rule "Rabatt salgskontor per apparatplass  per kunde per material 01"
when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == true)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZR05");
        suggestion.setKeyCombination("Rabatt salgskontor per apparatplass  per kunde per material");
        suggestion.setKeyCombinationTableName("A781");
end

rule "Rabatt salgskontor per apparatplass  per kunde per material per avfall 01"
when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == true)
        BoReportCondition(hasDevicePlacement == true)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZR05");
        suggestion.setKeyCombination("Rabatt salgskontor per apparatplass  per kunde per material per avfall");
        suggestion.setKeyCombinationTableName("?");
end

rule "Rabatt salgskontor per apparatplass  per kunde per material per apparattype 01"
    when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == true)
        BoReportCondition(isDeviceType == true)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZR05");
        suggestion.setKeyCombination("Rabatt salgskontor per apparatplass  per kunde per material per apparattype");
        suggestion.setKeyCombinationTableName("A780");
end

rule "Rabatt per kunde/material Tjeneste"
    when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZR02");
        suggestion.setKeyCombination("Rabatt per kunde/material");
        suggestion.setKeyCombinationTableName("A704");
end

rule "Rabatt salgskontor per kunde per material per avfall 02"
    when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == true)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZR02");
        suggestion.setKeyCombination("Rabatt salgskontor per kunde per material per avfall");
        suggestion.setKeyCombinationTableName("A785");
end

rule "Rabatt salgskontor per kunde per material per apparattype 02"
    when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == true)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZR02");
        suggestion.setKeyCombination("Rabatt salgskontor per kunde per material per apparattype");
        suggestion.setKeyCombinationTableName("A766");
end

rule "Rabatt salgskontor per apparatplass  per kunde per material 02"
    when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == true)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZR02");
        suggestion.setKeyCombination("Rabatt salgskontor per apparatplass  per kunde per material");
        suggestion.setKeyCombinationTableName("A781");
end

rule "Rabatt salgskontor per apparatplass  per kunde per material per avfall 02"
    when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == true)
        BoReportCondition(hasDevicePlacement == true)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZR02");
        suggestion.setKeyCombination("Rabatt salgskontor per apparatplass  per kunde per material per avfall");
        suggestion.setKeyCombinationTableName("A784");
end

rule "Rabatt salgskontor per apparatplass  per kunde per material per apparattype 02"
    when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == true)
        BoReportCondition(isDeviceType == true)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZR02");
        suggestion.setKeyCombination("Rabatt salgskontor per apparatplass  per kunde per material per apparattype");
        suggestion.setKeyCombinationTableName("A780");
end

rule "Rabatt per kunde/material Sone"
    when
        BoReportCondition(terms == "Generelle vilkår (metall)" || terms == "NG prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZPRK");
        suggestion.setKeyCombination("Rabatt per kunde/material");
        suggestion.setKeyCombinationTableName("A704");
end

rule "Rabatt salgskontor per kunde per material per avfall 03"
    when
        BoReportCondition(terms == "NG prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == true)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZPRK");
        suggestion.setKeyCombination("Rabatt salgskontor per kunde per material per avfall");
        suggestion.setKeyCombinationTableName("A785");
end

rule "Rabatt salgskontor per kunde per material per apparattype 03"
    when
        BoReportCondition(terms == "NG prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == true)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZPRK");
        suggestion.setKeyCombination("Rabatt salgskontor per kunde per material per apparattype");
        suggestion.setKeyCombinationTableName("A766");
end

rule "Rabatt salgskontor per kunde per sone  per material"
    when
        BoReportCondition(terms == "NG prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == true)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZPRK");
        suggestion.setKeyCombination("Rabatt salgskontor per kunde per sone  per material");
        suggestion.setKeyCombinationTableName("A795");
end

rule "Rabatt salgskontor per apparatplass  per kunde per material 03"
    when
        BoReportCondition(terms == "Generelle vilkår (metall)" || terms == "NG prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == true)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZPTR");
        suggestion.setKeyCombination("Rabatt salgskontor per apparatplass  per kunde per material");
        suggestion.setKeyCombinationTableName("A781");
end

rule "Rabatt salgskontor per apparatplass  per kunde per material per avfall 03"
    when
        BoReportCondition(terms == "NG prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == true)
        BoReportCondition(hasDevicePlacement == true)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZPRK");
        suggestion.setKeyCombination("Rabatt salgskontor per apparatplass  per kunde per material per avfall");
        suggestion.setKeyCombinationTableName("A784");
end

rule "Rabatt salgskontor per apparatplass  per kunde per material per apparattype 03"
    when
        BoReportCondition(terms == "NG prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == true)
        BoReportCondition(isDeviceType == true)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZPRK");
        suggestion.setKeyCombination("Rabatt salgskontor per apparatplass  per kunde per material per apparattype");
        suggestion.setKeyCombinationTableName("A780");
end

rule "Rabatt kunde/SD-dokument/Material"
    when
        BoReportCondition(terms == "Generelle vilkår" || terms == "NG prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == true)
    then
        suggestion.setConditionCode("ZPRK");
        suggestion.setKeyCombination("Rabatt kunde/SD-dokument/Material");
        suggestion.setKeyCombinationTableName("A798");
end

rule "Kundehiearki per material 01"
    when
        BoReportCondition(terms == "Generelle vilkår" || terms == "Ng prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == false)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == true)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZH00");
        suggestion.setKeyCombination("Kundehiearki per material");
        suggestion.setKeyCombinationTableName("A767");
end

rule "Kundehiearki per material per avfall 01"
    when
        BoReportCondition(terms == "Generelle vilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == false)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == true)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == true)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZH00");
        suggestion.setKeyCombination("Kundehiearki per material per avfall");
        suggestion.setKeyCombinationTableName("A786");
end

rule "Kundehiearki per material per apparattype 01"
    when
        BoReportCondition(terms == "Generelle vilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == false)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == true)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == true)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZH00");
        suggestion.setKeyCombination("Kundehiearki per material per apparattype");
        suggestion.setKeyCombinationTableName("A768");
end

rule "Kundehiearki per material 02"
    when
        BoReportCondition(terms == "Generelle vilkår" || terms == "Ng prisvikår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == false)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZH02");
        suggestion.setKeyCombination("Kundehiearki per material");
        suggestion.setKeyCombinationTableName("A767");
end

rule "Kundehiearki per material per avfall 02"
    when
        BoReportCondition(terms == "Generelle vilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == false)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == true)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == true)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZG02");
        suggestion.setKeyCombination("Kundehiearki per material per avfall");
        suggestion.setKeyCombinationTableName("A786");
end

rule "Kundehiearki per material per apparattype 02"
    when
        BoReportCondition(terms == "Generelle vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == false)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == true)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == true)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZH02");
        suggestion.setKeyCombination("Kundehiearki per material per apparattype");
        suggestion.setKeyCombinationTableName("A768");
end

rule "Kundehiearki per material 03"
    when
        BoReportCondition(terms == "Generelle vilkår" || terms == "Ng prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == false)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == true)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZH03");
        suggestion.setKeyCombination("Kundehiearki per material");
        suggestion.setKeyCombinationTableName("A767");
end

rule "Kundehiearki per material per avfall 03"
    when
        BoReportCondition(terms == "Generelle vilkår" || terms == "Ng prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == false)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == true)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == true)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZH03");
        suggestion.setKeyCombination("Kundehiearki per material per avfall");
        suggestion.setKeyCombinationTableName("A786");
end

rule "Kundehiearki per material per apparattype 03"
    when
        BoReportCondition(terms == "Generelle vilkår" || terms == "Ng prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == false)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == true)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == true)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZH03");
        suggestion.setKeyCombination("Kundehiearki per material per apparattype");
        suggestion.setKeyCombinationTableName("A805");
end

rule "Kundehiearki per SK per material"
    when
        BoReportCondition(terms == "Generelle vilkår" || terms == "Ng prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == true)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZH03");
        suggestion.setKeyCombination("Kundehiearki per SK per material");
        suggestion.setKeyCombinationTableName("A789");
end

rule "Kundehiearki per SK, sone og material"
    when
        BoReportCondition(terms == "Generelle vilkår" || terms == "Ng prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == true)
        BoReportCondition(isZoneMaterial == true)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZH03");
        suggestion.setKeyCombination("Kundehiearki per SK, sone og material");
        suggestion.setKeyCombinationTableName("A775");
end

rule "Kundehiearki per SK, material og apparattype"
    when
        BoReportCondition(terms == "Generelle vilkår" || terms == "Ng prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == true)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == true)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZH03");
        suggestion.setKeyCombination("Kundehiearki per SK, material og apparattype");
        suggestion.setKeyCombinationTableName("A805");
end

rule "Kundehiearki per SK, sone, material og apparattype"
    when
        BoReportCondition(terms == "Generelle vilkår" || terms == "Ng prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == true)
        BoReportCondition(isZoneMaterial == true)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == true)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZH03");
        suggestion.setKeyCombination("Kundehiearki per SK, sone, material og apparattype");
        suggestion.setKeyCombinationTableName("A770");
end

rule "Kundehiearki per sone og material"
    when
        BoReportCondition(terms == "Generelle vilkår" || terms == "Ng prisvilkår" || terms == "Kundens vilkår")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == false)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == true)
        BoReportCondition(isZoneMaterial == true)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZH03");
        suggestion.setKeyCombination("Salgskontor per material per sone");
        suggestion.setKeyCombinationTableName("A775");
end

rule "Salgsorg./DistrKanal/kunde"
    when
        BoReportCondition(terms == "Uavhengig av vilkår. Gjelder kun Adm. Gebyr")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == true)
        BoReportCondition(isCustomer == true)
        BoReportCondition(isNode == false)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZGEB");
        suggestion.setKeyCombination("Salgsorg./DistrKanal/kunde");
        suggestion.setKeyCombinationTableName("A765");
end

rule "Salgsorg./DistrKanal/node"
    when
        BoReportCondition(terms == "Uavhengig av vilkår. Gjelder kun Adm. Gebyr")
        BoReportCondition(hasSalesOrg == true)
        BoReportCondition(isPricedOnSalesOffice == false)
        BoReportCondition(isCustomer == false)
        BoReportCondition(isNode == true)
        BoReportCondition(isZoneMaterial == false)
        BoReportCondition(isWaste == false)
        BoReportCondition(hasDevicePlacement == false)
        BoReportCondition(isDeviceType == false)
        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZGEB");
        suggestion.setKeyCombination("Salgsorg./DistrKanal/node");
        suggestion.setKeyCombinationTableName("A778");
end

rule "Behandlingsgebyr"
    when
        BoReportCondition(terms == "Uavhengig av vilkår. Gjelder kun Behandlingsgebyr")
//        BoReportCondition(hasSalesOrg == false)
//        BoReportCondition(isPricedOnSalesOffice == false)
//        BoReportCondition(isCustomer == false)
//        BoReportCondition(isNode == false)
//        BoReportCondition(isZoneMaterial == false)
//        BoReportCondition(isWaste == false)
//        BoReportCondition(hasDevicePlacement == false)
//        BoReportCondition(isDeviceType == false)
//        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZBEH");
        suggestion.setKeyCombination("Behandlingsgebyr");
        suggestion.setKeyCombinationTableName("814: sorg/sk/kunde/apptype/varegruppe");
end

rule "Dersom miljøgebyr er satt til 0, må saken inn til OP."
    when
        BoReportCondition(terms == "Uavhengig av vilkår. Gjelder kun miljøgebyr")
//        BoReportCondition(hasSalesOrg == true)
//        BoReportCondition(isCustomer == true)
//        BoReportCondition(isNode == false)
//        BoReportCondition(isZoneMaterial == true)
//        BoReportCondition(isWaste == false)
//        BoReportCondition(hasDevicePlacement == false)
//        BoReportCondition(isDeviceType == false)
//        BoReportCondition(hasSalesDocument == false)
    then
        suggestion.setConditionCode("ZMIL");
        suggestion.setKeyCombination("Dersom miljøgebyr er satt til 0, må saken inn til OP.");
        suggestion.setKeyCombinationTableName("777:Sorg/oppdr.giv/material; 776:sorg/oppdr.giv/varegruppe;803:sorg/oppdr.giv/AP/Varegruppe");
end