create table users
(
    id                                  bigint  auto_increment not null
        primary key,
    ad_id                               varchar(255) null,
    associated_place                    varchar(255) null,
    department                          varchar(255) null,
    email                               varchar(255) null,
    email_regional_manager              varchar(255) null,
    email_sales_manager                 varchar(255) null,
    full_name                           varchar(255) null,
    job_title                           varchar(255) null,
    name                                varchar(255) null,
    org_name                            varchar(255) null,
    org_nr                              varchar(255) null,
    overall_power_of_attorney           varchar(255) null,
    phone_number                        varchar(255) null,
    power_of_attorneyfa                 int          null,
    power_of_attorneyoa                 int          null,
    region_name                         varchar(255) null,
    regional_managers_power_of_attorney varchar(255) null,
    resource_nr                         varchar(255) null,
    sure_name                           varchar(255) null,
    username                            varchar(255) null,
    username_alias                      varchar(255) null,
    sales_role_id                       bigint       null,
    constraint UK_6dotkott2kjsp8vw4d0m25fb7
        unique (email),
    constraint FK835ay557ujv9vwx8rgnm8lr11
        foreign key (sales_role_id) references sales_roles (id)
);

INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (1, 'e2f1963a-072a-4414-8a0b-6a3aa6988e0c', 'Oslo', null, 'alexander.brox@ngn.no', null, null, 'Alexander Brox', null, 'Alexander', null, null, null, '+4795838638', 2, 2, null, null, '63874', null, null, null, null);
INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (109, '183a1b82-d795-47d1-94a1-96f6aa5a268a', 'Oslo', 'Adact', 'thomas.nilsen@ngn.no', null, null, 'Thomas Nilsen', 'Utvikler', 'Thomas', 'Norsk Gjenvinning', '100', null, '+4793238365555', 3, 3, null, null, '100204', 'Nilsen', 'thomas.nilsen@ngn.no', 'vh3180', null);
INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (121, '380b1804-d7c8-4983-abee-7ff99a2a6f59', 'Larvik', 'Operativt Pristeam', 'Eirik.Flaa@ngn.no', null, null, 'Eirik Flaa', 'Leder Operativt pristeam', 'Eirik', 'ng', '100', null, '+4797069605', 3, 2, null, null, null, 'Flaa', 'Eirik.Flaa@ngn.no', 'vh1482', 8);
INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (123, 'dc804853-6a82-4022-8eb5-244fff724af2', 'Larvik', 'Adact', 'kjetil.torvund.minde@ngn.no', null, null, 'Kjetil Torvund Minde', 'Systemutvikler', 'Kjetil', null, null, null, '+4790135757', 5, 5, null, null, '63940', null, 'kjetil.torvund.minde@ngn.no', 'vh2308', 9);
INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (127, '7c6c0b5c-53de-4224-ac98-aa92c1aaa2ef', 'Larvik', 'Operativt pristeam', 'kristin.nerum@ngn.no', null, null, 'Kristin Jørgensen Nærum', 'Teamleder Operativt pristeam', 'Kristin Jørgensen', 'Norsk Gjenvinning', '100', null, '+4798232574', 2, 2, null, null, '60208', 'Nærum', 'kristin.nerum@ngn.no', 'vh1279', 9);
INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (128, 'b1f99e4b-60ac-4140-b071-d3dc9f5d65dd', 'Larvik', 'Annet', 'Gina.Hjelvik.Grotterud@ngn.no', null, null, 'Gina Hjelvik Grøtterud', 'Priskoordinator', 'Gina Hjelvik', 'Norsk Gjenvinning', '100', null, '+4799390193', 2, 2, null, null, '61032', 'Grøtterud', 'Gina.Hjelvik.Grotterud@ngn.no', 'vh1911', null);
INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (129, '1b161f8a-f01b-4af4-9eac-44c94ba33683', 'Torp', 'Østfold', 'jan.vidar.krathe@ngn.no', null, null, 'Jan Vidar Krathe', 'Salgssjef', 'Jan Vidar', null, null, null, '+4799383329', 2, 2, null, null, null, 'Krathe', 'jan.vidar.krathe@ngn.no', 'vh1315', null);
INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (148, 'fab1455e-9efe-49b4-a0de-979d0e828981', 'Oslo', null, 'fabricio.pirini@ngn.no', null, null, 'Fabricio Pirini', 'Developer', 'Fabricio', null, null, null, '+47412013592', 2, 2, null, null, '64083', null, 'fabricio.pirini@ngn.no', 'vh2621', 9);
INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (149, '47aef71e-345e-4533-9129-63c28b540f72', 'Larvik', 'Annet', 'sylvia.kivle@ngn.no', null, null, 'Sylvia Kivle', 'Priskoordinator', 'Sylvia', 'Norsk Gjennvinning', '100', null, '+4799699934', 2, 2, null, null, '60594', 'Kivle', 'sylvia.kivle@ngn.no', 'vh1091', null);
INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (150, '52a7fe7f-756f-4ac5-8062-8ae2f3d59342', 'Knarrevik', 'Order to cash', 'Anita.Olmheim@ngn.no', null, null, 'Anita Ølmheim', 'Priskoordinator sentralavtaler', 'Anita', 'NG', '100', null, '+4795229931', 2, 2, null, null, '61672', 'Ølmheim', 'Anita.Olmheim@ngn.no', 'vh1148', null);
INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (162, 'b03777d2-1659-4d13-adf9-71512f76b195', 'Oslo', 'Order to cash', 'monica.breen@ngn.no', null, null, 'Monica Cathrin Næss Breen', 'Leder order to cash', 'Monica Cathrin Næss', '01', '100', null, '+4790415952', 2, 2, null, null, null, 'Breen', 'monica.breen@ngn.no', 'vh1414', 9);
INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (163, '285e6409-6dbb-40e0-9539-dfb2a7007479', 'Oslo', 'Order to Cash', 'randi.langoy@ngn.no', null, null, 'Randi Langøy', 'Priskoordinator', 'Randi', '01', '100', null, '+4740155712', 2, 2, null, null, '60283', 'Langoy', 'randi.langoy@ngn.no', 'vh1204', 9);
INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (164, 'c66170a6-5fe7-46d8-9b73-a30089960995', 'Drammen', 'Buskerud', 'Ivan.Jensen@ngn.no', null, null, 'Ivan Wahlstedt Jensen', 'Regionssjef', 'Ivan Wahlstedt', 'NG', '100', null, '+4741230003', 2, 2, null, null, '62394', 'Jensen', 'Ivan.Jensen@ngn.no', 'vh1595', null);
INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (165, '4eac825f-df79-4ce2-a263-7a11bdf48bc1', 'Knarrevik', 'Hordaland', 'jan.vadseth@ngn.no', null, null, 'Jan Vidar Vadseth', 'Salgsleder', 'Jan Vidar', 'NG', '100', null, '+4797553009', 2, 2, null, null, null, 'Vadseth', 'jan.vadseth@ngn.no', 'vh1649', 6);
INSERT INTO pk_poal_db_prod.users (id, ad_id, associated_place, department, email, email_regional_manager, email_sales_manager, full_name, job_title, name, org_name, org_nr, overall_power_of_attorney, phone_number, power_of_attorneyfa, power_of_attorneyoa, region_name, regional_managers_power_of_attorney, resource_nr, sure_name, username, username_alias, sales_role_id) VALUES (166, '3c455419-9d6e-4fb5-826b-c14c319fe2b7', 'Larvik', 'Annet', 'Tommy.Welle@ngn.no', null, null, 'Tommy Welle Jacobsson', 'Markedskoordinator', 'Tommy Welle', 'NG', '100', null, '+4741767678', 2, 2, null, null, '62596', 'Jacobsen', 'Tommy.Welle@ngn.no', 'vh1326', 3);
