apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-custom
  namespace: kube-system
data:
  dev.server: | # you may select any name here, but it must end with the .server file extension
    dev.ding-ip-app-pk-service.no:53 {
    log
    errors
    rewrite stop {
      name regex (.*)\.dev.ding-ip-app-pk-service.no {1}.default.svc.cluster.local
      answer name (.*)\.default\.svc\.cluster\.local {1}.dev.ding-ip-app-pk-service.no
    }
    forward . /etc/resolv.conf # you can redirect this to a specific DNS server such as 10.0.0.10, but that server must be able to resolve the rewritten domain name
    }