apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db.properties: |
    c3ByaW5nLmRhdGFzb3VyY2UudXNlcm5hbWU9dGVzdEBway1wb2FsLWRiLXNydi1kZXYKc3ByaW5n
    LmRhdGFzb3VyY2UucGFzc3dvcmQ9RHFhWlhzdyUhXzEyMzQ=
