apiVersion: v1
kind: Secret
metadata:
  name: msal-secret
type: Opaque
data:
  msal.properties: |
    Z3JhcGgudXJsPWh0dHBzOi8vZ3JhcGgubWljcm9zb2Z0LmNvbS92MS4wCgpBVVRIT1JJVFk9aHR0
    cHM6Ly9sb2dpbi5taWNyb3NvZnRvbmxpbmUuY29tL2Q1ZGFjMzVkLWRhZDgtNGQ5NS04NWQxLTdl
    NmM0NWIzOWEyMy8KQ0xJRU5UX0lEPWRmNzMyNzA5LTIwNTAtNDE2OS1iZjkwLWJkMTk0MzE1MWZi
    ZgpTRUNSRVQ9bDNtOFF+M3JJbTZWQ2hHaGhCZWNUb21PLUVaMGJpaFdjczJnbmJwQQoKU0NPUEU9
    aHR0cHM6Ly9ncmFwaC5taWNyb3NvZnQuY29tLy5kZWZhdWx0CgpBRF9VU0VSX0lORk9fU0VMRUNU
    X0xJU1Q9aWQsZW1wbG95ZWVJZCx1c2VyUHJpbmNpcGFsTmFtZSxkaXNwbGF5TmFtZSxnaXZlbk5h
    bWUsc3VyZW5hbWUsZGVwYXJ0bWVudCxqb2JUaXRsZSxtYWlsLG1haWxOaWNrbmFtZSxtb2JpbGVQ
    aG9uZSxjaXR5
