apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    name: myapp
spec:
  containers:
  - name: ding-ip-app-pk-service
    image: ding-ip-app-pk-service
    # imagePullPolicy: Never
    ports:
      - containerPort: 80