CREATE TABLE if not exists customer_terms
(
    created_by                                 VARCHAR(25)                                NULL,
    create_date_time                           timestamp                                   NULL,
    modified_by                                VARCHAR(25)                                 NULL,
#     modified_date_time                         timestamp                                   NULL,
    number                                     INT                                         NULL,
    level                                      VARCHAR(255)                                NULL,
#     node_nr                                    VARCHAR(255)                                NULL,
    change_source                                      VARCHAR(255)                                NULL,
    sales_office                               INT                                         NULL,
    customer_name                              VARCHAR(255)                                NULL,
    customer_number                            VARCHAR(255)                                NULL,
    contract_term                              VARCHAR(255)                                NULL,
#     addition_for_admin_fee                     BIT(1)                                      NULL,
#     addition_for_road_tax                      BIT(1)                                      NULL,
#     agreement_end_date                         datetime                                    NULL,
#     agreement_start_date                       datetime                                    NULL,
#     customer_require_notification              BIT(1)                                      NULL,
#     index_rent                                 VARCHAR(255)                                NULL,
#     index_transport                            VARCHAR(255)                                NULL,
#     index_waste                                VARCHAR(255)                                NULL,
#     invoice_interval                           VARCHAR(255)                                NULL,
#     metal_pricing                              VARCHAR(255)                                NULL,
#     metal_set_date_for_offer                   datetime                                    NULL,
#     months_to_freeze_customer_from_adjustments INT                                         NULL,
#     new_or_established_customer                VARCHAR(255)                                NULL,
#     notification_mail_address                  VARCHAR(255)                                NULL,
#     payment_condition                          VARCHAR(255)                                NULL,
#     price_adjustment_date                      datetime                                    NULL,
    quarterly_adjustment                       VARCHAR(255)                                NULL,
#     required_number_of_days_notice             INT                                         NULL,
#     special_condition_action                   VARCHAR(255)                                NULL,
#     comment                                    VARCHAR(255)                                NULL,
    sales_office_id                            BIGINT                                      NOT NULL,
    customer_id                                BIGINT                                      NOT NULL,
    serial_number                              BIGINT                                      NOT NULL,
    CONSTRAINT pk_customer_terms PRIMARY KEY (sales_office_id, customer_id, serial_number)
);