create or replace table customer_terms
(
    id                                         bigint auto_increment primary key,
    created_by                                 varchar(25)                             null,
    create_date_time                           timestamp default '2021-06-10 20:47:05' null,
    modified_by                                varchar(25)                             null,
    modified_date_time                         timestamp default '2021-06-10 20:47:05' null,
    addition_for_admin_fee                     bit                                     null,
    addition_for_road_tax                      bit                                     null,
    agreement_end_date                         datetime(6)                             null,
    agreement_start_date                       datetime(6)                             null,
    comment                                    varchar(255)                            null,
    contract_term                              varchar(255)                            null,
    customer_name                              varchar(255)                            null,
    customer_number                            varchar(255)                            null,
    customer_require_notification              bit                                     null,
    index_rent                                 varchar(255)                            null,
    index_transport                            varchar(255)                            null,
    index_waste                                varchar(255)                            null,
    invoice_interval                           varchar(255)                            null,
    level                                      varchar(255)                            null,
    metal_pricing                              varchar(255)                            null,
    metal_set_date_for_offer                   datetime(6)                             null,
    months_to_freeze_customer_from_adjustments int                                     null,
    new_or_established_customer                varchar(255)                            null,
    node_nr                                    varchar(255)                            null,
    notification_mail_address                  varchar(255)                            null,
    number                                     int                                     null,
    payment_condition                          varchar(255)                            null,
    price_adjustment_date                      datetime(6)                             null,
    quarterly_adjustment                       varchar(255)                            null,
    region                                     varchar(255)                            null,
    required_number_of_days_notice             int                                     null,
    sales_employee                             varchar(255)                            null,
    sales_office                               varchar(255)                            null,
    change_source                              varchar(255)                            null,
    special_condition_action                   varchar(255)                            null,
    year_set                                   int                                     null,
    create_date                                timestamp default '2021-06-10 20:47:05' null,
    modified_date                              timestamp default '2021-06-10 20:47:05' null,
    sales_org                                  varchar(255)                            null
);

