apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: APIMPriskalkulatorIngress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /priskalkulator-dev
            pathType: Prefix
            backend:
              service:
                name: test
                port:
                  number: 8080