resources:
- ../base
- ingress.yaml

namespace: priskalkulator-dev
images:
- name: dingipacr.azurecr.io/ding-ip-app-pk-service
  newTag: v0.6.25
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
