apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'priskalkulator-service-dev:apps/Deployment:default/nginx-deployment'
  name: ding-kv-ip-pk-secret-store-dev
  namespace: priskalkulator-dev
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      serviceAccountRef:
        name: priskalkulator-sa-dev
      vaultUrl: 'https://ding-kv-ip-dev.vault.azure.net/'
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'priskalkulator-service-dev:apps/Deployment:default/nginx-deployment'
  name: ding-ip-app-pk-external-secret-dev
  namespace: priskalkulator-dev
spec:
  data:
    - remoteRef:
        key: pk-ad-app-id-uri
      secretKey: pkAdAppIdUri
    - remoteRef:
        key: pk-ad-user-info-select-list
      secretKey: pkAdUserInfoSelectList
    - remoteRef:
        key: pk-datasource-password
      secretKey: pkDatasourcePassword
    - remoteRef:
        key: pk-datasource-url
      secretKey: pkDatasourceUrl
    - remoteRef:
        key: pk-datasource-username
      secretKey: pkDatasourceUsername
    - remoteRef:
        key: pk-msal-ad-authority
      secretKey: pkMsalAdAuthority
    - remoteRef:
        key: pk-msal-client-id
      secretKey: pkMsalClientId
    - remoteRef:
        key: pk-msal-scope
      secretKey: pkMsalScope
    - remoteRef:
        key: pk-msal-secret
      secretKey: pkMsalSecret
    - remoteRef:
        key: pk-pdf-template-file-name
      secretKey: pkPdfTemplateFileName
    - remoteRef:
        key: pk-sap-api-contact-person-url
      secretKey: pkSapApiContactPersonUrl
    - remoteRef:
        key: pk-sap-api-customer-url
      secretKey: pkSapApiCustomerUrl
    - remoteRef:
        key: pk-sap-api-material-url
      secretKey: pkSapApiMaterialUrl
    - remoteRef:
        key: pk-sap-api-salesorg-url
      secretKey: pkApiSalesorgUrl
    - remoteRef:
        key: pk-sap-api-standard-price-url
      secretKey: pkSapApiStandardPriceUrl
    - remoteRef:
        key: pk-sap-username # Azure
      secretKey: pkSapUsername # K8s not that this name cannot be in any other format than camelCase
    - remoteRef:
        key: pk-sap-password
      secretKey: pkSapPassword
  refreshInterval: 2m # Refresh interval for given secret
  secretStoreRef:
    kind: SecretStore
    name: ding-kv-ip-pk-secret-store-dev
  target:
    name: ding-ip-app-pk-dev-secrets
    template:
      data:
        PK_AD_APP_ID_URI: '{{ .pkAdAppIdUri | toString }}'
        PK_MSAL_AD_USER_INFO_SELECT_LIST: '{{ .pkAdUserInfoSelectList | toString }}'
        PK_DATASOURCE_PASSWORD: '{{ .pkDatasourcePassword | toString }}'
        PK_DATASOURCE_URL: '{{ .pkDatasourceUrl | toString }}'
        PK_DATASOURCE_USERNAME: '{{ .pkDatasourceUsername | toString }}'
        PK_MSAL_AD_AUTHORITY: '{{ .pkMsalAdAuthority | toString }}'
        PK_MSAL_CLIENT_ID: '{{ .pkMsalClientId | toString }}'
        PK_MSAL_SCOPE: '{{ .pkMsalScope | toString }}'
        PK_MSAL_SECRET: '{{ .pkMsalSecret | toString }}'
        PK_SAP_API_CONTACT_PERSON_URL: '{{ .pkSapApiContactPersonUrl | toString }}'
        PK_SAP_API_CUSTOMER_URL: '{{ .pkSapApiCustomerUrl | toString }}'
        PK_SAP_API_MATERIAL_URL: '{{ .pkSapApiMaterialUrl | toString }}'
        PK_SAP_API_SALESORG_URL: '{{ .pkApiSalesorgUrl | toString }}'
        PK_SAP_API_STANDARD_PRICE_URL: '{{ .pkSapApiStandardPriceUrl | toString }}'
        PK_SAP_USERNAME: '{{ .pkSapUsername | toString }}'
        PK_SAP_PASSWORD: '{{ .pkSapPassword | toString }}'
        PK_PDF_TEMPLATE_FILE_NAME: '{{ .pkPdfTemplateFileName | toString }}'
      type: Opaque