apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'priskalkulator-service-dev:apps/Deployment:default/nginx-deployment'
  name: ding-kv-ip-pk-secret-store-dev
  namespace: priskalkulator-dev
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      serviceAccountRef:
        name: priskalkulator-sa-dev
      vaultUrl: 'https://ding-kv-ip-dev.vault.azure.net/'
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'priskalkulator-service-dev:apps/Deployment:default/nginx-deployment'
  name: ding-ip-app-pk-external-secret-dev
  namespace: priskalkulator-dev
spec:
  data:
    - remoteRef:
        key: pkSapUsername # Azure
      secretKey: pk-sap-username # K8s not that this name cannot be in any other format than camelCase
    - remoteRef:
        key: pkSapPassword
      secretKey: pk-sap-password
    - remoteRef:
        key: pkDatasourcePassword
      secretKey: pk-datasource-password
    - remoteRef:
        key: pkDatasourceUsername
      secretKey: pk-datasource-username
  refreshInterval: 2m # Refresh interval for given secret
  secretStoreRef:
    kind: SecretStore
    name: ding-kv-ip-pk-secret-store-dev
  target:
    name: ding-ip-app-pk-dev-secrets
    template:
      data:
        pk-sap-password: '{{ .pkSapPassword | toString }}'
        pk-sap-username: '{{ .pkSapUsername | toString }}'
        pk-datasource-password: '{{ .pkDatasourcePassword | toString }}'
        pk-datasource-username: '{{ .pkDatasourceUsername | toString }}'
      type: Opaque