apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'priskalkulator-service-dev:apps/Deployment:default/nginx-deployment'
  name: ding-kv-ip-pk-secret-store-dev
  namespace: priskalkulator-dev
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      serviceAccountRef:
        name: priskalkulator-sa-dev
      vaultUrl: 'https://ding-kv-ip-dev.vault.azure.net/'
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'priskalkulator-service-dev:apps/Deployment:default/nginx-deployment'
  name: ding-ip-app-pk-external-secret-dev
  namespace: priskalkulator-dev
spec:
  data:
    - remoteRef:
        key: pk-sap-username # Azure
        secretKey: pkSapUsername # K8s not that this name cannot be in any other format than camelCase
    - remoteRef:
        key: pk-sap-password
        secretKey: pkSapPassword
    - remoteRef:
        key: pk-datasource-url
        secretKey: pkDatasourceUrl
    - remoteRef:
        key: pk-datasource-password
        secretKey: pkDatasourcePassword
    - remoteRef:
        key: pk-datasource-username
        secretKey: pkDatasourceUsername
    - remoteRef:
        key: pk-sap-api-customer-url
        secretKey: pkSapApiCustomerUrl
    - remoteRef:
        key: pk-sap-api-contact-person-url
        secretKey: pkSapApiContactPersonUrl
    - remoteRef:
        key: pk-sap-api-standard-price-url
        secretKey: pkSapApiStandardPriceUrl
    - remoteRef:
        key: pk-sap-api-salesorg-url
        secretKey: pkApiSalesorgUrl
    - remoteRef:
        key: sap-api-material-url
        secretKey: pkSapApiMaterialUrl
    - remoteRef:
        key: pk-ad-app-id-uri
        secretKey: pkAdAppIdUri
  refreshInterval: 2m # Refresh interval for given secret
  secretStoreRef:
    kind: SecretStore
    name: ding-kv-ip-pk-secret-store-dev
  target:
    name: ding-ip-app-pk-dev-secrets
    template:
      data:
        pk-sap-password: '{{ .pkSapPassword | toString }}'
        pk-sap-username: '{{ .pkSapUsername | toString }}'
        pk-datasource-password: '{{ .pkDatasourcePassword | toString }}'
        pk-datasource-username: '{{ .pkDatasourceUsername | toString }}'
        pk-datasource-url: '{{ .pkDatasourceUrl | toString }}'
        pk-sap-api-customer-url: '{{ .pkSapApiCustomerUrl | toString }}'
        pk-sap-api-contact-person-url: '{{ .pkSapApiContactPersonUrl | toString }}'
        pk-sap-api-standard-price-url: '{{ .pkSapApiStandardPriceUrl | toString }}'
        pk-sap-api-salesorg-url: '{{ .pkApiSalesorgUrl | toString }}'
        sap-api-material-url: '{{ .pkSapApiMaterialUrl | toString }}'
        pk-ad-app-id-uri: '{{ .pkAdAppIdUri | toString }}'
      type: Opaque