apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'priskalkulator-service-dev:apps/Deployment:default/nginx-deployment'
  name: ding-kv-ip-dev
  namespace: priskalkulator-dev
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      serviceAccountRef:
        name: priskalkulator
      vaultUrl: 'https://ding-kv-ip-dev.vault.azure.net/'
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: 'priskalkulator-service-dev:apps/Deployment:default/nginx-deployment'
  name: ding-ip-app-pk-4vvhw
  namespace: priskalkulator-dev
spec:
  data:
    - remoteRef:
        key: pk-sap-username # Azure
      secretKey: pkSapUsername # K8s not that this name cannot be in any other format than camelCase
    - remoteRef:
        key: pk-sap-password
      secretKey: pkSapPassword
    - remoteRef:
        key: pk-datasource-password
      secretKey: pkDataSourcePassword
    - remoteRef:
        key: pk-datasource-username
      secretKey: pkDataSourceUsername
  refreshInterval: 2m # Refresh interval for given secret
  secretStoreRef:
    kind: SecretStore
    name: ding-kv-ip-dev
  target:
    name: ding-ip-app-pk-dev-secrets
    template:
      data:
        pk-sap-password: '{{ .pkSapPassword | toString }}'
        pk-sap-username: '{{ .pkSapUsername | toString }}'
        pk-datasource-password: '{{ .pkDataSourcePassword | toString }}'
        pk-datasource-username: '{{ .pkDataSourceUsername | toString }}'
      type: Opaque