name: Create minor version

on:
  pull_request:
    branches: [develop]

jobs:
  build:
    name: Build Maven Project
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          check-latest: true
          cache: 'maven'
      - name: Build with Maven
        run: mvn -B package --file pom.xml -Pprod

  version-bump:
    name: Bump Minor Version
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Retrieve Previous Release Version
        id: get_previous_version
        run: |
          previous_version=$(git describe --tags --abbrev=0)
          echo "previous_version=$previous_version" >> $GITHUB_OUTPUT

      - name: Increment Version
        id: increment_version
        run: |
          previous_version=${{ steps.get_previous_version.previous_version }}
          echo "Previous version: $previous_version"
          IFS='.' read -ra version_parts <<< "$previous_version"
          major=${version_parts[0]}
          echo "Major $major"
          minor=${version_parts[1]}
          echo "$minor"
          patch=${version_parts[2]}
          echo "$patch"
          new_version="v$major.$((minor + 1)).$patch"
          echo "New version: $new_version"
          echo "new_version=$new_version" >> $GITHUB_OUTPUT 

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Bump Version
        working-directory: manifest/dev/
        run: |
          previous_version=${{ steps.get_previous_version.outputs.previous_version }}
          echo "Previous Version: [$previous_version]"
          new_version=${{ steps.increment_version.outputs.new_version }}
          echo "New Version: [$new_version]"
          # Update your project files or use the appropriate command to bump the version
          pwd
          kustomize edit set image app-image=v${{ steps.increment_version.outputs.new_version }}

      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ steps.increment_version.outputs.new_version }}
          release_name: Release v${{ steps.increment_version.outputs.new_version }}
