name: Java CI Dev

on: 
  push:
    branches:
      - "develop"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

        # Runs a set of commands using the runners shell
      - name: Run maven script
        uses: guillonapa/action-maven-cli@master
        with:
          lifecycle: 'clean package test'