name: Validate feature and bug

on: 
  push:
    branches:
      - "feature/**"
      - "bug/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'
          check-latest: true
          cache: 'maven'
      - name: Build with Maven
        with:
          secrets: ${{ toJSON(secrets) }}
        env:
          ENVIRONMENT: dev
          PK_DATASOURCE_USERNAME: $PK_DATASOURCE_USERNAME
          PK_DATASOURCE_PASSWORD: $PK_DATASOURCE_PASSWORD
          PK_DATASOURCE_URL: $PK_DATASOURCE_URL
          PK_SAP_USERNAME: $PK_SAP_USERNAME
          PK_SAP_PASSWORD: $PK_SAP_PASSWORD
          PK_SAP_API_CUSTOMER_URL: $PK_SAP_API_CUSTOMER_URL
          PK_SAP_API_CONTACT_PERSON_URL: $PK_SAP_API_CONTACT_PERSON_URL
          PK_SAP_API_STANDARD_PRICE_URL: $PK_SAP_API_STANDARD_PRICE_URL
          PK_SAP_API_SALESORG_URL: $PK_SAP_API_SALESORG_URL
          PK_SAP_API_MATERIAL_URL: $PK_SAP_API_MATERIAL_URL
          PK_PDF_TEMPLATE_FILE_NAME: $PK_PDF_TEMPLATE_FILE_NAME
          PK_AD_APP_ID_URI: $PK_AD_APP_ID_URI
          PK_MSAL_AD_AUTHORITY: $PK_MSAL_AD_AUTHORITY
          PK_MSAL_CLIENT_ID: $PK_MSAL_CLIENT_ID
          PK_MSAL_SECRET: $PK_MSAL_SECRET
          PK_MSAL_SCOPE: $PK_MSAL_SCOPE
          PK_MSAL_AD_USER_INFO_SELECT_LIST: $PK_MSAL_AD_USER_INFO_SELECT_LIST
        run: mvn -Dspring.profiles.active=$ENVIRONMENT -B package --file pom.xml